### ISSUE TITLE
Define a data format for predictors

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/acton#1]
Define a data format for predictor IO.

On the input side, predictors should receive training examples and training labels. These examples might not be specified in terms of their features &mdash; perhaps they will be referred to by an ID and predictors will have access to a corresponding pool of data.

On the output side, predictors should output real-valued predictions for each example, including both unlabelled and labelled examples. Multiple predictions could be output for each example.

**Comment by MatthewJA** [comment]
On reflection, I think that we should probably use HDF5 for anything with large NumPy arrays. We *shouldn't* use it for anything structured &mdash; it's not what the format is for, and it's been mildly painful to do so in my experience. So perhaps we could use a combination of HDF5 and protobufs.

This is a similar approach to that taken by joblib.

**Comment by chengsoonong** [comment]
Let's try to get everything in protobuf first, and discuss whether we need more efficiency later.
https://gist.github.com/monkeybutter/b91004077be5d73a478a

**Comment by MatthewJA** [comment]
Sounds good to me. Note that an option is to use protobufs to store components of messages and then serialise all that in HDF5 &mdash; e.g. (ID, label) tuples could be put in a protobuf and then compiled into an HDF5 file. This is a better approach than using HDF5 directly as you would otherwise lose the structure, such as in crowdastro where I divided the ATLAS and WISE datasets into a numeric and a string array.

I'll write up two `.proto` files then!
