### ISSUE TITLE
SDSS: generate regression data from source

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#12]
Follow Alasdair's SQL query for getting data for classifying {star, galaxy, quasar} from photometry.
https://github.com/chengsoonong/mclass-sky/blob/master/projects/alasdair/notebooks/01_dataset_prepration.ipynb
(2.8 million labelled items)

Update query to include the column on spectroscopic redshift. This will give a dataset for binary classification, multiclass and regression.

We'll have to discuss about hosting or scripting to create this data.

**Comment by jakubnabaglo** [comment]
The spectroscopic redshift is already in the query. Unless you mean something else?

**Comment by jakubnabaglo** [comment]
Matt suggests query comment may be wrong. Says to find out how the final redshift is computed, could be from photometric sources.

**Comment by chengsoonong** [comment]
Let us use this redshift value for now. Please download the file from
http://filestore.nicta.com.au/mlrg-data/astro/sdss_dr7_photometry_source.csv.gz

I was not sure how long the nicta filestore would be online.
