### ISSUE TITLE
crowdastro find agn

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#31]
From pre-computed features in a HDF5 file.

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.58316.svg)](https://doi.org/10.5281/zenodo.58316)

**Comment by MatthewJA** [comment]
Unfortunately my MMR implementation is pretty slow &mdash; I need to sit down and think about how to improve it before the code scales to crowdastro data.

**Comment by MatthewJA** [comment]
Blocked on #48. Maybe it's not MMR after all! I suspect the ID querying — if that's the case, I'll swap everything to integer IDs.

**Comment by MatthewJA** [comment]
MMR is *also* quite slow but nevertheless managed to get some data out for uncertainty sampling.
