### ISSUE TITLE
Multiclass classification example

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#32]
Figure 5.2 and 5.3 of Alasdair's thesis.
https://github.com/chengsoonong/mclass-sky/blob/master/projects/alasdair/thesis/tran15honours-thesis.pdf

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.58500.svg)](https://doi.org/10.5281/zenodo.58500)

**Comment by MatthewJA** [comment]
To generate data for a passive learning curve, it should be as simple as:

```bash
acton --data data/sdss.h5 --pandas-key sdss -f psfMag_r_w14 -l clas -o sdss.pb --epochs 10
```

It's *really* slow for me, probably because there's 2.8 million data points and I'm on an Air.

**Comment by MatthewJA** [comment]
Decision from meeting: Use <1% of the data.

**Comment by MatthewJA** [comment]
Subset attached.

[sdss_subset.h5.zip](https://github.com/chengsoonong/acton/files/769733/sdss_subset.h5.zip)

**Comment by MatthewJA** [comment]
![plot](https://cloud.githubusercontent.com/assets/2681312/22867296/ca71a84e-f1d9-11e6-850b-796635b8c851.png)

I should really add a seed.

**Comment by MatthewJA** [comment]
![plot](https://cloud.githubusercontent.com/assets/2681312/22960732/599b1530-f394-11e6-904b-fec0fed31956.png)
