### ISSUE TITLE
Should we support Python 2?

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/acton#4]
- Many in the scientific community still use Python 2, but
- Writing a completely new code-base in an outdated language seems a bad idea, and
- Writing and maintaining code that runs on both Python 2 and Python 3 is significantly more complicated than just supporting Python 3

**Comment by chengsoonong** [comment]
Let's support only python 3 for v0.1 and v0.2.

If we decide around Christmas that we need python 2, I suggest using [six](https://pypi.python.org/pypi/six).
