### ISSUE TITLE
Reimplement Chris' command-line predictor

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/acton#50]
Write a wrapper class for Chris' C-based predictor.

**Comment by MatthewJA** [comment]
Code here: https://www.mso.anu.edu.au/~cwolf/

[PRG] mc_class_empirW_2014..> 22-Dec-2016 12:33   10K  
[TXT] meansquare_empirw_de..> 22-Dec-2016 12:31   14K  
[TXT] meansquare_estimator.c  22-Dec-2016 12:32   16K

**Comment by MatthewJA** [comment]
Working on this now.

**Comment by MatthewJA** [comment]
No dice. I spent a while getting ESO-MIDAS working so I can actually run the code now, but I don't know the formats of the input tables so I can't get any output. I could look at the code itself to work it out but I think it'd be better if I worked on other issues for now and talked to Chris at some point.

**Comment by chengsoonong** [comment]
Schedule a chat with Chris.

**Comment by MatthewJA** [comment]
Shall do.

**Comment by MatthewJA** [comment]
Meeting with Chris next week. I'll figure out how to do this then.

**Comment by MatthewJA** [comment]
Chris walked me through how his predictor works. It's pretty simple to reimplement in the simple case, where we generate probabilities for each class. The extension of this is to generate redshift-dependent class probabilities `P_i(z)`, but I'm not sure how to do that in this framework.

**Comment by chengsoonong** [comment]
I think it is beyond the scope of this project to implement fancy predictors. Just the basic one will do.

**Comment by MatthewJA** [comment]
I agree. I think that the `KDEClassifier` does basically the same thing as Chris' predictor, assuming equal uncertainty on all data points. That doesn't hold in general but since we don't have any way to represent those uncertainties it doesn't matter. I'll close this,
