### ISSUE TITLE
Types?

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#64]
It would probably be useful for unit testing to have types. Not clear how much it will benefit us short term.
https://pypi.python.org/pypi?name=typing&version=3.5.3.0&:action=display

**Comment by MatthewJA** [comment]
I tried to get a type checker working before, unsuccessfully, but not *that* type checker. I'll have a look at it tomorrow.

Type checking is probably beneficial and would have caught some of the errors I've fixed.

**Comment by MatthewJA** [comment]
Ah, `typing` just provides expressions; another library is needed for doing type-checking. I did try `mypy` but had some difficulty in getting it to actually work. I can give it another shot, though.
