### ISSUE TITLE
Add command-line interface for components

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/acton#70]

**Comment by MatthewJA** [comment]
I'll plan out what the interface should look like, starting with predictors since we already have protobufs for that.

```bash
acton-predict
    --data data.dat
    --training-set indices.txt
    --predictor LogisticRegression
    --feature feature_column
    --label label_column
    --output predictions.pb
```

Input will be the dataset to train and predict on. The indices to use for training will be specified in a text file `--training-set`.

Output will be a serialised Predictions protobuf.

**Comment by MatthewJA** [comment]
Another option would be something like

```bash
acton-predict
    --data data.dat
    --feature feature_column
    --label label_column
    --training-set indices.txt
    --predictor LogisticRegression
    --output predictions.pb
```

so you could drop your data right in without having Acton pre-process it first. It's a bit messier and the output is still (necessarily) a protobuf.

**Comment by MatthewJA** [comment]
The recommender is a lot simpler.

```bash
acton-recommend
    --predictions predictions.pb
    --recommendation-set indices.txt
    --recommender UncertaintyRecommender
    --recommendation-count 1
    --diversity 0.1
```

I'd be very happy for this to output to stdout.

**Comment by MatthewJA** [comment]
Another option for `acton-predict` is that it can take either the arguments directly *or* the protobuf, and then just construct a protobuf from there.

**Comment by MatthewJA** [comment]
@chengsoonong: Note that if you want to run the CLIs I'm adding now, you'll need to reinstall Acton since the new CLIs are added on install.

`pip3 install -e .` will work for that.

**Comment by chengsoonong** [comment]
My advice is to begin at the desired end product.

The way to see whether these CLI are elegant or not is to write the bash script that reproduces
simulate_active_learning

**Comment by MatthewJA** [comment]
Something like this would work and looks alright:

```bash
for (( ; ; )); do
    acton-predict --labels labels.pb -o predictions.pb
    acton-recommend --predictions predictions.pb | acton-label -o labels.pb
done
```

Though there's no entry points for accessory information (database etc.) here. We could also try:

```bash
for (( ; ; )); do
    acton-predict --labels labels.pb -o predictions.pb
    acton-recommend --predictions predictions.pb -o recommendations.pb
    acton-label --recommendations recommendations.pb -o labels.pb
done
```

and carry accessory information around in protobufs. We could even pipe protobufs directly between processes if no output is specified:

```bash
for (( ; ; )); do
    acton-predict < labels.pb | acton-recommend | acton-label > labels.pb
done
```

That's kinda nice in a way.

(The more I think about this, the more I think auxiliary information *should* be stored in protobufs — no sense in specifying the database every time.)

**Comment by MatthewJA** [comment]
Here's what using `acton-label` looks like:

```
$ echo "1
> 2
> 3
> 4
> 5
> 6
> " | acton-label --data tests/data/classification.txt -l col20
WARNING:root:Not implemented: labeller_accuracy
{"db":{"className":"ASCIIReader","kwarg":[{"value":"\"\"","key":"feature_cols"},{"value":"\"col20\"","key":"label_col"}],"path":"tests/data/classification.txt"},"id":["1","2","3","4","5","6"]}
```

It currently outputs human-readable JSON. That could change to be binary data in the future.

**Comment by MatthewJA** [comment]
`acton-predict` is also (basically) done (f60d17e6f) and works like this:

```
acton-label --data tests/data/classification.txt -l col20 | acton-predict > predictions.pb
```

**Comment by MatthewJA** [comment]
`acton-recommend` in a24a55b80256957afbf25afc148c9268bf348d27.

**Comment by MatthewJA** [comment]
Just have to tidy up the edges (`acton-recommend | acton-label`) and add a test of some sort.

**Comment by MatthewJA** [comment]
Finished the loop in e73678ed81a2297fa8cfa81ba1309632e704f63b. Still have to fix up some code and write a test.
