### ISSUE TITLE
Set up Read the Docs

### ISSUE THREAD

**Issue by MatthewJA** [chengsoonong/acton#8]
I can do this one.

**Comment by MatthewJA** [comment]
Alright, I've set up Read the Docs, but the webhook needs to be set up by the repo owner. Instructions are [here](http://docs.readthedocs.io/en/latest/webhooks.html).

**Comment by chengsoonong** [comment]
Flicked the switch on github. Added badge in 0fb6f9053d441bb9b847a162359b2139920baae7
