### ISSUE TITLE
‘ImportError: No module named 'acton.proto'’

### ISSUE THREAD

**Issue by wgmg165** [chengsoonong/acton#92]
Hi!
After I have succesfully  pip installed acton on windows10, I get an ImportError: No module named 'acton.proto'  when I import acton.database. I have on idea about it. If you can give me a advice, many thanks!

**Comment by MatthewJA** [comment]
Is `protobuf` installed correctly? Note that this will not be installed by `pip`; you'll have to install it manually. Instructions are [here](https://github.com/google/protobuf/tree/master/python).

You can check by trying to import `google.protobuf`.

**Comment by chengsoonong** [comment]
Closing this after a month without response from @wgmg165
